import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next PWA",
  description: "Generated by create-next-pwa",
  manifest: "/manifest.json"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add meta tags for theme color and icons */}
        <meta name="theme-color" content={'#000000'} />
        <link rel="icon" href="/icon-192x192.png" sizes="192x192" type="image/png" />
        <link rel="favicon" href="/favicon.ico" sizes="any" type="image/x-icon" />
        <link rel="icon" href="/icon-256x256.png" sizes="256x256" type="image/png" />
        <link rel="icon" href="/icon-384x384.png" sizes="384x384" type="image/png" />
        <link rel="icon" href="/icon-512x512.png" sizes="512x512" type="image/png" />
        <link rel="apple-touch-icon" href="/icon-192x192.png" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
